// ─── DELICATE WORLD — DATA ───────────────────────────────────────────────────
// Edit this file to update characters, images, and descriptions.
// Image paths are relative to the index.html file.

const DUALITY = {
  solar: {
    label: "Solar Lee",
    sub: "The girl staring back at her when the mask comes off.",
    images: [
      "images/Solar Lee/solar-smoking.jpg",
      "images/Solar Lee/solar-holdingadrink.jpg",
      "images/Solar Lee/solar-pouringadrink.jpg",
      "images/Solar Lee/solar-bloodonhands.jpg",
      "images/Solar Lee/solar-tongueout.jpg",
      "images/Solar Lee/solar-newyorkcity.jpg",
      "images/Solar Lee/solar-selfie.jpg",
      "images/Solar Lee/solar.jpg",
    ],
  },
  soomi: {
    label: "Kim Soomi",
    sub: "Korea's number one solo artist. Perfect. Beloved. Untouchable.",
    images: [
      "images/Solar Lee/soomi-photoshoot.jpg",
      "images/Solar Lee/soomi-photoshoot2.jpg",
      "images/Solar Lee/soomi-applyinglipgloss.jpg",
      "images/Solar Lee/soomipfp.jpg",
      "images/Solar Lee/soomipfp2.jpg",
      "images/Solar Lee/soomi.jpg",
      "images/Solar Lee/soomi2.jpg",
      "images/Solar Lee/soomi3.jpg",
    ],
  },
};

const GROUPS = [
  {
    id: "solar",
    label: "Solar Lee",
    sub: "The center of everything.",
    characters: [
      {
        id: "solar",
        name: "Solar Lee",
        alias: "Kim Soomi",
        role: "Protagonist",
        pfp: "images/Solar Lee/solarpfp.jpg",
        accent: "#8e44ad",
        born: 1995,
        age2019: 24,
        desc: "Born Solar Lee in New York. Daughter of Jaesang Lee — chosen to inherit the company. Fled to Korea at eighteen after an incident she does not speak about. Built Kim Soomi from nothing in a city she did not know. Has been running from Solar Lee ever since. Confident, goofy, emotionally uncontrolled. She paints herself as pure and independent and is neither. She loves too hard and it rules and nearly destroys her life.",
        arc: "Learns that Solar Lee and Kim Soomi are not enemies. They are the same girl — flawed, capable, loved, and worth staying for.",
        typeoflove: null,
        connections: [
          "Jinhwan — infatuation. Euphoria. A force that keeps pulling them back together through every fight.",
          "Jungkook — childlike love. Built on friendship, trust, and growth. They feel young when they are together.",
          "Sunwoo — the original. Danger dressed as loyalty. So bad it is good, and she has never fully stopped.",
          "Chanhee — knows everything. Has always known. The one she calls when the mask is off.",
          "Yein — the little sister she would burn everything down for.",
        ],
        images: [
          "images/Solar Lee/solar.jpg",
          "images/Solar Lee/solar2.jpg",
          "images/Solar Lee/solar3.jpg",
          "images/Solar Lee/solar4.jpg",
          "images/Solar Lee/solar-selfie.jpg",
          "images/Solar Lee/solar-selfie2.jpg",
          "images/Solar Lee/solar-at-bday-party.jpg",
          "images/Solar Lee/solar-smoking.jpg",
          "images/Solar Lee/solar-smoking2.jpg",
          "images/Solar Lee/solar-smoking3.jpg",
          "images/Solar Lee/solar-holdingadrink.jpg",
          "images/Solar Lee/solar-pouringadrink.jpg",
          "images/Solar Lee/solar-bloodonhands.jpg",
          "images/Solar Lee/solar-newyorkcity.jpg",
          "images/Solar Lee/solar-tongueout.jpg",
          "images/Solar Lee/soomi.jpg",
          "images/Solar Lee/soomi2.jpg",
          "images/Solar Lee/soomi3.jpg",
          "images/Solar Lee/soomi4.jpg",
          "images/Solar Lee/soomi5.jpg",
          "images/Solar Lee/soomi-photoshoot.jpg",
          "images/Solar Lee/soomi-photoshoot2.jpg",
          "images/Solar Lee/soomi-applyinglipgloss.jpg",
        ],
      },
    ],
  },

  {
    id: "bts",
    label: "BTS",
    sub: "Her world in Korea before YG. The people she ran from in 2018.",
    characters: [
      {
        id: "jungkook",
        name: "Jeon Jungkook",
        alias: "Kookie",
        role: "The Connection",
        pfp: "images/Jungkook/jkpfp.jpg",
        accent: "#2980b9",
        born: 1995,           // corrected from 1997
        age2019: 24,          // corrected from 22
        desc: "BTS's golden maknae. Connected with Solar instantly in 2013 — laughing like old friends from the very first five minutes. Competitive, jealous, a wanna-be bad boy by Korean standards. Fit, long hair, piercings, dresses grunge. The in-between of innocence and vulgarity. He blew everything up in 2018 not out of selfishness but out of panic, and has been living with that ever since.",
        arc: "Learns that being there for someone and being with someone are not the same thing — and that letting go with grace is the hardest thing he has ever done.",
        typeoflove: "Childlike love. Built on friendship, trust, connection, and growth. They feel young and free when they are together.",
        connections: [
          "Solar — the most natural connection of her life, and the one she closed the door on in 2018.",
          "Jimin (BTS) — loves him like a brother. Has always known Jimin has feelings for Solar.",
          "Sunwoo — trusts him more than Jinhwan does. Tells him things Solar would not want him to.",
        ],
        images: [
          "images/Jungkook/jk-2013.jpg",
          "images/Jungkook/jk-2018.jpg",
          "images/Jungkook/jk-2021.jpg",
          "images/Jungkook/jk-2022.jpg",
          "images/Jungkook/jk-2022-2.jpg",
          "images/Jungkook/jk-photoshoot-2022.jpg",
          "images/Jungkook/jk.jpg",
          "images/Jungkook/jkselfie.jpg",
        ],
      },
      {
        id: "jimin",
        name: "Park Jimin",
        alias: "Chimmie",
        role: "Best Friend (Korea)",
        pfp: "images/Jimin/jiminpfp.jpg",
        accent: "#f39c12",
        born: 1995,
        age2019: 24,
        desc: "BTS. Solar's closest friend in Korea — warm, listening, similar to Jacob from back home. He found her after she arrived in Seoul and became her anchor. He fell in love with her along the way and could not always control it. On a New York rooftop in 2017, something mutual happened. Jungkook has always known. The three of them love each other — and it is complicated.",
        arc: "Loves Solar genuinely, loves Jungkook like a brother, and carries the weight of both without resolution.",
        typeoflove: "Warmth that became something more — never fully acted on.",
        connections: [
          "Solar — her Chimmie. The one she texts when things fall apart.",
          "Jungkook — brothers. The tension between them regarding Solar is always present.",
        ],
        images: [
          "images/Jimin/jimin.jpg",
          "images/Jimin/jimin2.jpg",
          "images/Jimin/jimin3.jpg",
        ],
      },
      {
        id: "jin",
        name: "Kim Seokjin",
        alias: "Jin",
        role: "BTS — Supporting",
        pfp: "images/Jin/jinpfp.jpg",
        accent: "#aaa",
        born: 1992,
        age2019: 27,
        desc: "BTS's eldest. The cook of the group — whenever he visits Solar's apartment he makes a feast from whatever ingredients she has. A warm, steady presence in her Korean life.",
        arc: null,
        typeoflove: null,
        connections: ["Solar — one of the boys she misses most after the 2018 cut-off."],
        images: ["images/Jin/jin.jpg"],
      },
      {
        id: "hoseok",
        name: "Jung Hoseok",
        alias: "Hobi",
        role: "BTS — Supporting",
        pfp: "images/Hoseok/hobipfp.jpg",
        accent: "#aaa",
        born: 1994,
        age2019: 25,
        desc: "BTS. One of the boys Solar was close with during her Big Hit years. Known for raiding her freezer for chocolate treats the moment he walks in the door.",
        arc: null,
        typeoflove: null,
        connections: ["Solar — part of the Big Hit circle she left behind in 2018."],
        images: ["images/Hoseok/hobipfp2.jpg"],
      },
      {
        id: "namjoon",
        name: "Kim Namjoon",
        alias: "RM",
        role: "BTS — Supporting",
        pfp: "images/Namjoon/joonpfp.jpg",
        accent: "#aaa",
        born: 1994,
        age2019: 25,
        desc: "BTS's leader. A steady, thoughtful presence in Solar's Korean orbit.",
        arc: null,
        typeoflove: null,
        connections: ["Solar — part of the Big Hit world."],
        images: ["images/Namjoon/joonpfp2.jpg"],
      },
      {
        id: "yoongi",
        name: "Min Yoongi",
        alias: "Suga",
        role: "BTS — Supporting",
        pfp: "images/Yoongi/yoongipfp.jpg",
        accent: "#aaa",
        born: 1993,
        age2019: 26,
        desc: "BTS. Famously hard to get a genuine hug from — Solar always forces one out of him anyway, and his gummy smile always appears against his will.",
        arc: null,
        typeoflove: null,
        connections: ["Solar — offers to help with music. Solar always pulls him into hugs he pretends to hate."],
        images: [],
      },
      {
        id: "taehyung",
        name: "Kim Taehyung",
        alias: "V",
        role: "BTS — Supporting",
        pfp: "images/Taehyung/taepfp.jpg",
        accent: "#aaa",
        born: 1995,
        age2019: 24,
        desc: "BTS. One of the younger members Solar is warm with. Plays Overwatch with her and Jungkook.",
        arc: null,
        typeoflove: null,
        connections: ["Solar — gaming partner. One of the boys who cheers loudest for her comebacks."],
        images: ["images/Taehyung/tae.jpg"],
      },
    ],
  },

  {
    id: "ikon",
    label: "iKON",
    sub: "Her second family at YG. The boys next door.",
    characters: [
      {
        id: "jinhwan",
        name: "Kim Jinhwan",
        alias: "Nani / Jinan",
        role: "The Warmth",
        pfp: "images/Jinhwan/jinanpfp.jpg",
        accent: "#27ae60",
        born: 1994,
        age2019: 25,
        desc: "iKON's eldest. Found Solar in a terrible state in 2018 and quietly made it his mission to pull her back. Patient, compassionate, awkward when nervous — he rambles. Not fit like the others, does not know how to fight or use a gun. Always chooses peace. He is frail in the ways the others are not, and that is his power. He is the first one you think she ends up with — and then you learn he is more deceptive than he appeared.",
        arc: "The one you root for. The one who turns out to be more complicated than he seemed. Love that makes you fight more and want more at the same time.",
        typeoflove: "Head over heels. Love at first sight. Infatuation — euphoria. A type of love that makes you forget.",
        connections: [
          "Solar — chose her first and keeps choosing her even when she does not choose back.",
          "Jungkook — competitive hatred turned grudging respect. A gun pointed between them at least once.",
          "Jimin (AOA) — his ex. The villain. The one who uses his history against him and against Solar.",
        ],
        images: [
          "images/Jinhwan/jinan-2020.jpg",
          "images/Jinhwan/jinan-2022.jpg",
          "images/Jinhwan/jinan-chapter44.jpg",
          "images/Jinhwan/jinan-city.jpg",
          "images/Jinhwan/jinan-city2.jpg",
          "images/Jinhwan/jinan-eatingout.jpg",
          "images/Jinhwan/jinan-pose.jpg",
          "images/Jinhwan/jinanselfie.jpg",
          "images/Jinhwan/jinanselfie2.jpg",
          "images/Jinhwan/jinanselfie3.jpg",
        ],
      },
      {
        id: "junhoe",
        name: "Koo Junhoe",
        alias: "June",
        role: "Best Friend (Korea) / iKON",  // corrected
        pfp: "images/Junhoe/junepfp.jpg",
        accent: "#aaa",
        born: 1997,
        age2019: 22,
        desc: "iKON. Solar's best friend in Korea alongside Jimin — the tallest of the group and the first to make a terrible joke in any bad situation. Her most reliable source of idiotic humor when everything is falling apart. One of the few people whose presence genuinely makes her laugh without trying.",
        arc: null,
        typeoflove: null,
        connections: [
          "Solar — best friends. One of her closest people in Korea.",
          "Jinhwan — constantly winding him up. Fiercely loyal to both of them.",
        ],
        images: ["images/Junhoe/junepfp2.jpg"],
      },
      {
        id: "bobby",
        name: "Kim Jiwon",
        alias: "Bobby",
        role: "iKON — Supporting",
        pfp: "images/Bobby/bobbypfp.jpg",
        accent: "#aaa",
        born: 1995,
        age2019: 24,
        desc: "iKON. One of the louder, more energetic members. The first one to cheer when Jinhwan walks out of the hospital — with the worst possible choice of words.",
        arc: null,
        typeoflove: null,
        connections: ["Solar — part of the iKON family she lives alongside at YG."],
        images: ["images/Bobby/bobbyselfie.jpg"],
      },
      {
        id: "donghyuk",
        name: "Kim Donghyuk",
        alias: "DK",
        role: "iKON — Supporting",
        pfp: "images/Donghyuk/dongpfp.jpg",
        accent: "#aaa",
        born: 1997,
        age2019: 22,
        desc: "iKON. One of the youngest members, always quick to help. Runs to get water for Solar when Jinhwan demands it.",
        arc: null,
        typeoflove: null,
        connections: ["Solar — part of the iKON circle she calls her second family."],
        images: ["images/Donghyuk/dongselfie.jpg"],
      },
      {
        id: "hanbin",
        name: "Kim Hanbin",
        alias: "B.I.",
        role: "iKON — Supporting",
        pfp: "images/Hanbin/hanbinpfp.jpg",
        accent: "#aaa",
        born: 1996,
        age2019: 23,
        desc: "iKON's leader and main producer. Solar spends some of her last days before everything changes holed up in Hanbin's studio, writing and recording until the boys drag her out.",
        arc: null,
        typeoflove: null,
        connections: ["Solar — lets her use his studio as a refuge in her darkest hours."],
        images: ["images/Hanbin/hanbin.jpg"],
      },
      {
        id: "chanwoo",
        name: "Jung Chanwoo",
        alias: "Chanwoo",
        role: "iKON — Supporting",
        pfp: "images/Chanwoo/chanwoopfp.jpg",
        accent: "#aaa",
        born: 1998,
        age2019: 21,
        desc: "iKON's youngest member.",
        arc: null,
        typeoflove: null,
        connections: ["Solar — part of the iKON family."],
        images: ["images/Chanwoo/chanwoo.jpg"],
      },
      {
        id: "yunhyeong",
        name: "Song Yunhyeong",
        alias: "Song",
        role: "iKON — Supporting",
        pfp: "images/Yunhyeong/yunpfp.jpg",
        accent: "#aaa",
        born: 1995,
        age2019: 24,
        desc: "iKON. The cook of the group, similar to Jin in BTS. Always making sure everyone has eaten.",
        arc: null,
        typeoflove: null,
        connections: ["Solar — part of the iKON circle."],
        images: [],
      },
    ],
  },

  {
    id: "lees",
    label: "The Lee Family",
    sub: "The castle. The people she was exiled from and had to find her way back to.",
    characters: [
      {
        id: "jaehyun",
        name: "Lee Jaehyun",
        alias: "Jae",
        role: "The Eldest Brother",
        pfp: "images/Jaehyun Lee/jaepfp.jpg",
        accent: "#95a5a6",
        born: 1994,
        age2019: 25,
        desc: "Solar's eldest brother. One year older, far more cautious. Always had suspicions about Sunwoo's father going back to 2006. Attended parties to make sure things did not go too far. Held the family together while Solar was gone for years. In Peace, Sunwoo personally invites him into the gang.",
        arc: "The protector who has his own anger to reckon with — toward the father who broke the family, and toward a sister who left him to hold it alone.",
        typeoflove: null,
        connections: [
          "Solar — protective, complicated, loyal.",
          "Sunwoo — joins the gang by personal invitation in Peace.",
          "Their father — anger that has hardened over years of watching.",
        ],
        images: [
          "images/Jaehyun Lee/jae.jpg",
          "images/Jaehyun Lee/jae2.jpg",
          "images/Jaehyun Lee/jae-teen.jpg",
          "images/Jaehyun Lee/jae-teen2.jpg",
        ],
      },
      {
        id: "chaerin",
        name: "Lee Chaerin",
        alias: "Chae",
        role: "The Middle Sister",
        pfp: "images/Chaerin Lee/chaerinselfie.jpg",
        accent: "#d35400",
        born: 1999,           // corrected from 1998 — four years younger than Solar (1995)
        age2019: 20,          // corrected from 21
        desc: "Four years younger than Solar. Blackmailed her way into the party scene at sixteen and ended up just as deep. Stayed in the Lee house while Solar left and watched their father try to mold her into a replacement. Sharp, dry, more loyal than she lets on. She is the one who grabs Solar's hand in the rain before they go inside.",
        arc: "Learns that surviving is not the same as living — and that her sister coming home is a beginning they can both build on.",
        typeoflove: null,
        connections: [
          "Solar — complicated love. Admiration and resentment in equal measure.",
          "Yein — becomes her closest person in Peace, stepping into Solar's place.",
          "Juyeon — went through the party years together.",
        ],
        images: [
          "images/Chaerin Lee/chaerin1.jpg",
          "images/Chaerin Lee/chaerin2-teenager.jpg",
          "images/Chaerin Lee/chaerin3.jpg",
          "images/Chaerin Lee/chaerin4.jpg",
          "images/Chaerin Lee/chaerinselfie2.jpg",
        ],
      },
      {
        id: "juyeon",
        name: "Lee Juyeon",
        alias: null,
        role: "The Middle Brother",
        pfp: "images/Juyeon Lee/juyeonpfp.jpg",
        accent: "#7f8c8d",
        born: 1999,           // corrected to match Chaerin — same age, slightly older, not twins
        age2019: 20,          // corrected
        desc: "Solar's younger brother. Same age as Chaerin but slightly older — not twins. Got pulled into the party scene the same night Chaerin did, overhearing them in the hallway and demanding to come along. Protective of his sisters in his own way.",
        arc: null,
        typeoflove: null,
        connections: [
          "Solar — protective younger brother energy.",
          "Chaerin — went through the party years side by side.",
        ],
        images: [
          "images/Juyeon Lee/juyeonselfie.jpg",
          "images/Juyeon Lee/juyeonselfie2.jpg",
        ],
      },
      {
        id: "yein",
        name: "Lee Yein",
        alias: "Baby Yein",
        role: "The Little Sister",
        pfp: "images/Yein Lee/yeinpfp.jpg",
        accent: "#48c774",
        born: 2009,
        age2019: 10,
        desc: "Born in 2009. Solar's youngest sibling. Eleven during the New York return arc — listening to K-pop on her tablet while her father yells at her downstairs about grades. She is the child version of everything Solar survived. She adores Solar completely. By Peace she is fourteen, texting her sister unanswered messages, quietly terrified of losing her again.",
        arc: "The one Solar most wants to rewrite. Her story is still being written.",
        typeoflove: null,
        connections: [
          "Solar — the sister she dreamed of running to her whole childhood.",
          "Chaerin — becomes her closest sibling during Peace.",
        ],
        images: [
          "images/Yein Lee/yein-2020.jpg",
          "images/Yein Lee/yein-2022.jpg",
          "images/Yein Lee/yein-2022-2.jpg",
          "images/Yein Lee/yein-child.jpg",
          "images/Yein Lee/yein-child2.jpg",
          "images/Yein Lee/yein-doinghomework.jpg",
        ],
      },
      {
        id: "jaesang",
        name: "Lee Jaesang",
        alias: "Father",
        role: "The Father",
        pfp: "images/Jaesang & Solji Lee/jaesang.jpg",
        accent: "#7f8c8d",
        born: 1965,
        age2019: 54,
        desc: "Head of the Lee family and owner of one of the most successful businesses in New York. Cold, controlling, prone to anger breakdowns. Chose Solar as his successor at thirteen and spent years pressuring her into a life she never asked for. Kicked her out and called her a disgrace. His apology, years later, is the event the Lee family never thought would come.",
        arc: "A man who let his anger oversee everything — who realizes too late what it cost him.",
        typeoflove: null,
        connections: [
          "Solar — exiled her. Eventually apologizes. She forgives him conditionally.",
          "The family — his coldness shaped every one of his children.",
        ],
        images: [
          "images/Jaesang & Solji Lee/jaesang2.jpg",
          "images/Jaesang & Solji Lee/jaesang3.jpg",
          "images/Jaesang & Solji Lee/jaesang4.jpg",
        ],
      },
      {
        id: "solji",
        name: "Lee Solji",
        alias: "Mother",
        role: "The Mother",
        pfp: "images/Jaesang & Solji Lee/solji2.jpg",
        accent: "#7f8c8d",
        born: 1967,
        age2019: 52,
        desc: "The Lee siblings' mother. Always tried to appear collected to the outside world — insisting the family was perfect, that they had no problems. Harsh on the children because her husband demanded it, not because she wanted to be. Without him she had nothing, and she knew it. She never wanted to hurt any of them.",
        arc: "A woman who survived by compliance — and who has to reckon with what that compliance cost her children.",
        typeoflove: null,
        connections: [
          "The children — loved them in the only way she knew how, which was never enough.",
          "Jaesang — dependent on him in ways she could not escape.",
        ],
        images: [
          "images/Jaesang & Solji Lee/solji.jpg",
          "images/Jaesang & Solji Lee/solji3.jpg",
        ],
      },
    ],
  },

  {
    id: "gang",
    label: "Sunwoo's Gang",
    sub: "Boys he saved. They idolized him.",
    characters: [
      {
        id: "sunwoo",
        name: "Kim Sunwoo",
        alias: "Sweetheart",
        role: "The Past",
        pfp: "images/Sunwoo/sunwoopfp.jpg",
        accent: "#c0392b",
        born: 1995,
        age2019: 24,
        desc: "Son of Ji Dongwoo — one of New York's most corrupt men. Gang leader. Trained to fight, steal, and kill since age five. Covered in scars and tattoos. Witty, sarcastic, deeply violent, almost entirely emotionally blank — except with Solar, the only person he has ever fully trusted. He is what every other love interest is not. There is no Korean idol version of Sunwoo. He is the real thing.",
        arc: "Survived the December events and a heart transplant. Now in New York, picking up the pieces — CEO of his father's company, rebuilding what remains of the gang, carrying the weight of everyone he lost. His love for Solar Lee was the only real thing in a life built on violence, and he is still here.",
        typeoflove: "Protectiveness as devotion. Obsession dressed as loyalty. He has viewed her as royalty since they were ten years old.",
        connections: [
          "Solar — the first love. His reason. His most protected secret.",
          "The gang — boys he saved from impossible circumstances. They idolized him.",
          "Jaehyun — personally invites him into the gang in Peace.",
        ],
        images: [
          "images/Sunwoo/sunwoo.jpg",
          "images/Sunwoo/sunwoo-2012.jpg",
          "images/Sunwoo/sunwoo-blurrycandid.jpg",
          "images/Sunwoo/sunwoo-inthecity.jpg",
          "images/Sunwoo/sunwoo-newyork.jpg",
          "images/Sunwoo/sunwoo-newyork2.jpg",
          "images/Sunwoo/sunwoo-smiling.jpg",
          "images/Sunwoo/sunwooselfie.jpg",
          "images/Sunwoo/sunwooselfie2.jpg",
          "images/Sunwoo/sunwooselfie3.jpg",
        ],
      },
      {
        id: "sangyeon",
        name: "Lee Sangyeon",
        alias: null,
        role: "Gang — First Member",
        pfp: null,
        accent: "#c0392b",
        born: 1996,
        age2019: 23,
        desc: "The first. Sunwoo found him getting beaten at home, living in poverty, house practically falling apart. Sunwoo offered him a way out. He accepted. Sunwoo enrolled him in online courses to learn coding and hacking — he became the gang's tech backbone.",
        arc: "Survived. Leads what remains of the gang after the December events.",
        typeoflove: null,
        connections: ["Sunwoo — owes him everything. Idolized him.", "The gang — the one who keeps them together."],
        images: [],
      },
      {
        id: "hyunjae",
        name: "Lee Jaehyun (Hyunjae)",
        alias: "Hyunjae",
        role: "Gang — Second Member (deceased)",
        pfp: null,
        accent: "#c0392b",
        born: 1997,
        age2019: 22,
        desc: "The second. Sunwoo found him in an alley getting jumped over a bad drug deal. He was trying to escape an alcoholic father and save money to leave. Sunwoo pulled a gun on his attackers and got him out. Dies during the December events.",
        arc: "One of three who do not make it out of December.",
        typeoflove: null,
        connections: ["Sunwoo — saved his life.", "The gang — one of the founding members."],
        images: [],
      },
      {
        id: "hyunjoon",
        name: "Kim Hyunjoon",
        alias: "Hyunjoon",
        role: "Gang — Third Member",
        pfp: null,
        accent: "#c0392b",
        born: 1997,
        age2019: 22,
        desc: "The third. Found hanging around abandoned buildings, pulled out a fancy knife when Sunwoo asked what skills he had. Had no idea what to do with his life. The one who supplied Solar with drugs when Sunwoo cut her off — he never could say no to her and Sunwoo never fully forgave him for it.",
        arc: null,
        typeoflove: null,
        connections: ["Sunwoo — third member, loyal.", "Solar — gave her drugs behind Sunwoo's back. Great friends."],
        images: [],
      },
      {
        id: "eric",
        name: "Eric",
        alias: null,
        role: "Gang — Fourth Member",
        pfp: null,
        accent: "#c0392b",
        born: 1997,
        age2019: 22,
        desc: "The fourth. Found homeless under a bridge, setting up a makeshift shelter. Hostile at first. Sunwoo told him he could offer him something better. Eventually he accepted. The one who whispered that Sunwoo could not be dead — telling himself more than anyone else.",
        arc: null,
        typeoflove: null,
        connections: ["Sunwoo — saved him from the street."],
        images: [],
      },
      {
        id: "younghoon",
        name: "Lee Younghoon",
        alias: "Younghoon",
        role: "Gang — Fifth Member (deceased)",
        pfp: null,
        accent: "#c0392b",
        born: 1997,
        age2019: 22,
        desc: "The fifth. Rescued from an orphanage that had been in the news for mistreating its residents. Smart enough that the other members flagged him as an asset. Sunwoo went and got him out. Dies during the December events.",
        arc: "One of three who do not make it out of December.",
        typeoflove: null,
        connections: ["Sunwoo — rescued him.", "The gang — well-liked, trusted."],
        images: [],
      },
      {
        id: "haknyeon",
        name: "Ju Haknyeon",
        alias: "Haknyeon",
        role: "Gang — Sixth Member (deceased)",
        pfp: null,
        accent: "#c0392b",
        born: 1998,
        age2019: 21,
        desc: "The sixth. Found shooting at police outside a gas station — how he made his living, he said, and the first time he had ever been caught. Sunwoo pulled up and let him get in. Dies during the December events.",
        arc: "One of three who do not make it out of December.",
        typeoflove: null,
        connections: ["Sunwoo — gave him an escape.", "The gang — the youngest founding member."],
        images: [],
      },
    ],
  },

  {
    id: "newyork",
    label: "The New York Crew",
    sub: "Her childhood. The people who knew Solar before Soomi ever existed.",
    characters: [
      {
        id: "chanhee",
        name: "Choi Chanhee",
        alias: null,
        role: "Best Friend (New York)",
        pfp: null,
        accent: "#e056a0",
        born: 1995,
        age2019: 24,
        desc: "Solar's childhood best friend. Knows more about her than anyone alive. Was furious when he understood what Sunwoo's father did to Changmin's family — forgave Solar anyway, as he always does. The one who holds her when the mask fully comes off. The first one to run to her in every crisis.",
        arc: "The constant. The one who sees all three versions of her — Solar the child, Kim Soomi the idol, and the girl trying to find her way back.",
        typeoflove: "Not romantic. The oldest kind of love — the one that does not need a name.",
        connections: [
          "Solar — knows about the drugs, the miscarriage, Sunwoo, all of it.",
          "The crew — Changmin, Kevin, Jacob. All of them show up at different points.",
        ],
        images: [],
      },
      {
        id: "changmin",
        name: "Changmin",
        alias: null,
        role: "New York Crew",
        pfp: null,
        accent: "#aaa",
        born: 1995,
        age2019: 24,
        desc: "One of Solar's childhood friends. His father was the VP of the Lee company — murdered in 2006, an act Sunwoo's father was behind. Chanhee was the first to piece it together. Changmin's loss is the wound underneath a lot of the story's tension.",
        arc: null,
        typeoflove: null,
        connections: ["Solar — childhood friend. His father's death is a permanent shadow between Solar and Sunwoo.", "Chanhee — best friends."],
        images: [],
      },
      {
        id: "kevin",
        name: "Kevin Moon",
        alias: null,
        role: "New York Crew",
        pfp: null,
        accent: "#aaa",
        born: 1995,
        age2019: 24,
        desc: "One of Solar's childhood friends. Loud, enthusiastic, prone to having what Chanhee calls a conniption in front of every celebrity in South Korea. The comic relief of the crew. Approached Solar in 2010 about confusion over his sexuality.",
        arc: null,
        typeoflove: null,
        connections: ["Solar — childhood friend. Shows up in Korea for her birthday party.", "Chanhee — best friends. Kevin drives him insane."],
        images: [],
      },
      {
        id: "jacob",
        name: "Jacob Bae",
        alias: null,
        role: "New York Crew",
        pfp: null,
        accent: "#aaa",
        born: 1995,
        age2019: 24,
        desc: "One of Solar's childhood friends. A warm, steady presence — the Jacob from back home that Jimin in Korea partially mirrors for Solar.",
        arc: null,
        typeoflove: null,
        connections: ["Solar — one of her most trusted from home.", "The crew — the calm one."],
        images: [],
      },
    ],
  },
];

const RELATIONSHIPS = [
  {
    id: "solkook",
    label: "Solar & Jungkook",
    years: "2013 – present",
    accent: "#2980b9",
    desc: "The most natural connection of her life. They met in 2013 as trainees staying late, talked like old friends from the first five minutes. Fell in love slowly, got engaged, lost everything in 2018 when the stalker forced Jungkook's hand. Found their way back across three years of silence.",
    images: [
      "images/Solar & Jungkook/solkook-2017.jpg",
      "images/Solar & Jungkook/solkook-2018.jpg",
      "images/Solar & Jungkook/solkook-2018-2.jpg",
      "images/Solar & Jungkook/solkook-2018-3.jpg",
      "images/Solar & Jungkook/solkook-2019.jpg",
      "images/Solar & Jungkook/solkook-2020.jpg",
      "images/Solar & Jungkook/solkook-2020-2.jpg",
      "images/Solar & Jungkook/solkook-2021.jpg",
      "images/Solar & Jungkook/solkook-2021-2.jpg",
      "images/Solar & Jungkook/solkook-2021-3.jpg",
      "images/Solar & Jungkook/solkook-cooking-together.jpg",
      "images/Solar & Jungkook/solkook-cuteselfie.jpg",
      "images/Solar & Jungkook/solkook-cuteselfie2.jpg",
      "images/Solar & Jungkook/solkook-hugging-2018.jpg",
      "images/Solar & Jungkook/solkook-hugging-2020.jpg",
      "images/Solar & Jungkook/solkook-kissing.jpg",
      "images/Solar & Jungkook/solkook-kissing2.jpg",
      "images/Solar & Jungkook/solkook-photoshoot.jpg",
      "images/Solar & Jungkook/solkook-photoshoot-2022.jpg",
      "images/Solar & Jungkook/solkook-polaroids.jpg",
      "images/Solar & Jungkook/solkook-polaroids2.jpg",
      "images/Solar & Jungkook/solkook-polaroids3.jpg",
      "images/Solar & Jungkook/solkook-selfie.jpg",
      "images/Solar & Jungkook/solkook-selfie2.jpg",
      "images/Solar & Jungkook/solkook-solars-bday-party.jpg",
    ],
  },
  {
    id: "solwoo",
    label: "Solar & Sunwoo",
    years: "2005 – always",
    accent: "#c0392b",
    desc: "The original. They met at ten, banned from each other by their families, found each other anyway. Seven years together through high school. She left. He never stopped.",
    images: [
      "images/Solar & Sunwoo/solwoo-2012.jpg",
      "images/Solar & Sunwoo/solwooselfie.jpg",
    ],
  },
  {
    id: "solchae",
    label: "Solar & Chaerin",
    years: "always",
    accent: "#d35400",
    desc: "Complicated love. Chaerin blackmailed her way into Solar's world and ended up just as deep. She is the one who grabs Solar's hand in the rain.",
    images: [
      "images/Chaerin and Solar/solchae-night-of-solars-bday.jpg",
      "images/Chaerin and Solar/solchae-selfie.jpg",
      "images/Chaerin and Solar/solchae-selfie2.jpg",
      "images/Chaerin and Solar/solchae1.jpg",
      "images/Chaerin and Solar/solchae2.jpg",
      "images/Chaerin and Solar/solchae3.jpg",
    ],
  },
  {
    id: "soljae",
    label: "Solar & Jaehyun",
    years: "always",
    accent: "#95a5a6",
    desc: "The eldest two. He always showed up — at parties to pull her out of rooms, at the airport to say goodbye, at the family home to hold things together.",
    images: [
      "images/Jaehyun and Solar/soljae-polaroid.jpg",
      "images/Jaehyun and Solar/soljae-polaroid2.jpg",
      "images/Jaehyun and Solar/soljae-teens-selfie.jpg",
      "images/Jaehyun and Solar/soljae-teens.jpg",
      "images/Jaehyun and Solar/soljae-teens2.jpg",
      "images/Jaehyun and Solar/soljae-teens3.jpg",
      "images/Jaehyun and Solar/soljae.jpg",
      "images/Jaehyun and Solar/soljae2.jpg",
    ],
  },
  {
    id: "solye",
    label: "Solar & Yein",
    years: "2009 – always",
    accent: "#48c774",
    desc: "Solar left when Yein was four. Yein has spent her whole life waiting for her big sister to come back. Solar would burn the world down for her.",
    images: [
      "images/Yein and Solar/solye-2013.jpg",
      "images/Yein and Solar/solye-2013-2.jpg",
      "images/Yein and Solar/solye-2020.jpg",
      "images/Yein and Solar/solye-2022.jpg",
      "images/Yein and Solar/solye-selfie-2020.jpg",
      "images/Yein and Solar/solye-selfie-plane.jpg",
    ],
  },
];
